=== tecnickcom/gogen/src/srvnosql/resources/etc/project/config.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "~#PROJECT#~ config",
  "description": "JSON schema for ~#PROJECT#~ configuration",
  "type": "object",
  "properties": {
    "remoteConfigProvider": {
      "description": "Remote configuration source (if any)",
      "type": "string",
      "default": "",
      "enum": [
        "",
        "consul",
        "etcd"
      ]
    },
    "remoteConfigEndpoint": {
      "description": "Remote configuration URL (ip:port)",
      "type": "string",
      "default": ""
    },
    "remoteConfigPath": {
      "description": "Remote configuration path in which to search for the configuration file (e.g. '/config/~#PROJECT#~')",
      "type": "string",
      "default": ""
    },
    "remoteConfigSecretKeyring": {
      "description": "Path to the openpgp secret keyring used to decrypt the remote configuration data (e.g. '/etc/~#PROJECT#~/configkey.gpg'); if empty a non secure connection will be used instead",
      "type": "string",
      "default": ""
    },
    "serverAddress": {
      "description": "Internal HTTP address (ip:port) or just (:port)",
      "type": "string",
      "default": ":8017"
    },
    "log": {
      "description": "Logging settings",
      "type": "object",
      "properties": {
        "level": {
          "description": "Defines the default log level",
          "type": "string",
          "default": "DEBUG",
          "enum": [
            "EMERGENCY",
            "ALERT",
            "CRITICAL",
            "ERROR",
            "WARNING",
            "NOTICE",
            "INFO",
            "DEBUG"
          ]
        },
        "network": {
          "description": "(OPTIONAL) Network type used by the Syslog",
          "type": "string",
          "default": "",
          "enum": [
            "",
            "udp",
            "tcp"
          ]
        },
        "address": {
          "description": "(OPTIONAL) Network address of the Syslog daemon (ip:port) or just (:port)",
          "type": "string",
          "default": ""
        }
      },
      "additionalProperties": false,
      "required": [
        "level",
        "network",
        "address"
      ]
    },
    "stats": {
      "description": "StatsD is used to collect usage metrics",
      "type": "object",
      "properties": {
        "prefix": {
          "description": "StatsD client's string prefix that will be used in every bucket name",
          "type": "string",
          "default": "~#PROJECT#~"
        },
        "network": {
          "description": "Network type used by the StatsD client",
          "type": "string",
          "default": "udp",
          "enum": [
            "udp",
            "tcp"
          ]
        },
        "address": {
          "description": "Network address of the StatsD daemon (ip:port) or just (:port)",
          "type": "string",
          "default": ":8125"
        },
        "flush_period": {
          "description": "Sets how often (in milliseconds) the StatsD client's buffer is flushed. When 0 the buffer is only flushed when it is full",
          "type": "integer",
          "default": 100,
          "minimum": 0,
          "maximum": 1000
        }
      },
      "additionalProperties": false,
      "required": [
        "prefix",
        "network",
        "address",
        "flush_period"
      ]
    },
    "mongodb": {
      "description": "MongoDB Settings",
      "type": "object",
      "properties": {
        "address": {
          "description": "MongoDB address: [mongodb://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options]",
          "type": "string",
          "default": "mongodb://127.0.0.1:27017"
        },
        "database": {
          "description": "Database name",
          "type": "string",
          "default": "annotation-service"
        },
        "user": {
          "description": "Database user",
          "type": "string",
          "default": ""
        },
        "password": {
          "description": "Database password",
          "type": "string",
          "default": ""
        },
        "timeout": {
          "description": "Connection timeout in seconds",
          "type": "integer",
          "default": 60
        }
      },
      "additionalProperties": false,
      "required": [
        "address",
        "database"
      ]
    },
    "elasticsearch": {
      "description": "ElasticSearch Settings",
      "type": "object",
      "properties": {
        "url": {
          "description": "ElasticSearch url",
          "type": "string",
          "default": "http://127.0.0.1:9200"
        },
        "index": {
          "description": "ElasticSearch main Index",
          "type": "string",
          "default": ""
        },
        "username": {
          "description": "ElasticSearch user name",
          "type": "string",
          "default": ""
        },
        "password": {
          "description": "ElasticSearch password",
          "type": "string",
          "default": ""
        }
      },
      "additionalProperties": false,
      "required": [
        "url",
        "index"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "serverAddress",
    "log",
    "stats",
    "mongodb",
    "elasticsearch"
  ]
}

=== tecnickcom/gogen/src/srvnosql/resources/test/etc/project/config.json
{
  "remoteConfigProvider" : "",
  "remoteConfigEndpoint" : "",
  "remoteConfigPath" : "",
  "remoteConfigSecretKeyring" : "",
  "serverAddress": ":8017",
  "log": {
    "level": "DEBUG",
    "network": "",
    "address": ""
  },
  "stats": {
    "prefix": "~#PROJECT#~",
    "network": "udp",
    "address": ":8125",
    "flush_period": 100
  },
  "mongodb": {
    "address": "ds035428.mongolab.com:35428",
    "database": "goinggo",
    "user": "guest",
    "password": "welcome",
    "timeout": 60
  },
  "elasticsearch": {
    "url": "http://127.0.0.1:9200",
    "index": "test",
    "username": "",
    "password": ""
  }
}

=== tecnickcom/gogen/src/srvnosql/resources/etc/project/config.json
{
  "remoteConfigProvider" : "",
  "remoteConfigEndpoint" : "",
  "remoteConfigPath" : "",
  "remoteConfigSecretKeyring" : "",
  "serverAddress": ":8017",
  "log": {
    "level": "INFO",
    "network": "",
    "address": ""
  },
  "stats": {
    "prefix": "~#PROJECT#~",
    "network": "udp",
    "address": ":8125",
    "flush_period": 100
  },
  "mongodb": {
    "address": "mongodb://127.0.0.1:27017",
    "database": "test",
    "user": "",
    "password": "",
    "timeout": 60
  },
  "elasticsearch": {
    "url": "http://127.0.0.1:9200",
    "index": "test",
    "username": "",
    "password": ""
  }
}
