=== tecnickcom/gogen/examples/service/resources/etc/gogenexample/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "description": "JSON schema for gogenexample configuration",
  "properties": {
    "clients": {
      "additionalProperties": false,
      "description": "Configuration for external service clients",
      "properties": {
        "ipify": {
          "additionalProperties": false,
          "description": "Configuration for the ipify service client",
          "examples": [
            {
              "address": "https://api.ipify.org",
              "timeout": 15
            }
          ],
          "properties": {
            "address": {
              "default": "",
              "description": "Base URL of the service",
              "examples": [
                "https://api.ipify.org"
              ],
              "title": "Address",
              "type": "string"
            },
            "timeout": {
              "default": 15,
              "description": "HTTP client timeout [seconds]",
              "examples": [
                15
              ],
              "title": "Timeout",
              "type": "integer"
            }
          },
          "required": [
            "address",
            "timeout"
          ],
          "title": "ipify service client",
          "type": "object"
        }
      },
      "required": [
        "ipify"
      ],
      "title": "Clients",
      "type": "object"
    },
    "db": {
      "additionalProperties": false,
      "description": "Configuration of the databases",
      "properties": {
        "enabled": {
          "default": false,
          "description": "Enable or disable the database",
          "type": "boolean"
        },
        "main": {
          "additionalProperties": false,
          "description": "Configuration of the main database (read/write)",
          "examples": [
            {
              "conn_max_idle_count": 2,
              "conn_max_idle_time": 60,
              "conn_max_lifetime": 3600,
              "conn_max_open": 5,
              "dsn": "username:password@protocol(address)/dbname?param=value",
              "timeout_ping": 1
            }
          ],
          "properties": {
            "conn_max_idle_count": {
              "default": 5,
              "description": "Maximum number of connections in the idle connection pool",
              "examples": [
                5
              ],
              "type": "integer"
            },
            "conn_max_idle_time": {
              "default": 1,
              "description": "Maximum amount of time a connection may be idle [seconds]",
              "examples": [
                60
              ],
              "type": "integer"
            },
            "conn_max_lifetime": {
              "default": 1,
              "description": "Maximum amount of time a connection may be reused [seconds]",
              "examples": [
                3600
              ],
              "type": "integer"
            },
            "conn_max_open": {
              "default": 50,
              "description": "Maximum number of open connections to the database. If n <= 0, there is no limit on the number of open connections",
              "examples": [
                50
              ],
              "type": "integer"
            },
            "dsn": {
              "default": "",
              "description": "Database in DSN format: username:password@protocol(address)/dbname?param=value",
              "type": "string"
            },
            "timeout_ping": {
              "default": 1,
              "description": "Database healthcheck ping timeout [seconds]",
              "examples": [
                1
              ],
              "type": "integer"
            }
          },
          "required": [
            "conn_max_idle_count",
            "conn_max_idle_time",
            "conn_max_lifetime",
            "conn_max_open",
            "dsn",
            "timeout_ping"
          ],
          "title": "Main database configuration",
          "type": "object"
        },
        "read": {
          "additionalProperties": false,
          "description": "Configuration of the read-replica database (read-only)",
          "examples": [
            {
              "conn_max_idle_count": 2,
              "conn_max_idle_time": 60,
              "conn_max_lifetime": 3600,
              "conn_max_open": 5,
              "dsn": "username:password@protocol(address)/dbname?param=value",
              "timeout_ping": 1
            }
          ],
          "properties": {
            "conn_max_idle_count": {
              "default": 5,
              "description": "Maximum number of connections in the idle connection pool",
              "examples": [
                5
              ],
              "type": "integer"
            },
            "conn_max_idle_time": {
              "default": 1,
              "description": "Maximum amount of time a connection may be idle [seconds]",
              "examples": [
                60
              ],
              "type": "integer"
            },
            "conn_max_lifetime": {
              "default": 1,
              "description": "Maximum amount of time a connection may be reused [seconds]",
              "examples": [
                3600
              ],
              "type": "integer"
            },
            "conn_max_open": {
              "default": 50,
              "description": "Maximum number of open connections to the database. If n <= 0, there is no limit on the number of open connections",
              "examples": [
                50
              ],
              "type": "integer"
            },
            "dsn": {
              "default": "",
              "description": "Database in DSN format: username:password@protocol(address)/dbname?param=value",
              "type": "string"
            },
            "timeout_ping": {
              "default": 1,
              "description": "Database healthcheck ping timeout [seconds]",
              "examples": [
                1
              ],
              "type": "integer"
            }
          },
          "required": [
            "conn_max_idle_count",
            "conn_max_idle_time",
            "conn_max_lifetime",
            "conn_max_open",
            "dsn",
            "timeout_ping"
          ],
          "title": "Read-replica database configuration",
          "type": "object"
        }
      },
      "required": [
        "main",
        "read"
      ],
      "title": "Database configuration",
      "type": "object"
    },
    "enabled": {
      "default": true,
      "description": "Enable or disable the service",
      "title": "Enabled",
      "type": "boolean"
    },
    "log": {
      "additionalProperties": false,
      "description": "Logger settings",
      "properties": {
        "address": {
          "default": "",
          "description": "(OPTIONAL) Network address of the (r)Syslog daemon (ip:port) or just (:port)",
          "type": "string"
        },
        "format": {
          "default": "JSON",
          "description": "Defines the default log format",
          "enum": [
            "CONSOLE",
            "JSON"
          ],
          "type": "string"
        },
        "level": {
          "default": "DEBUG",
          "description": "Defines the default log level",
          "enum": [
            "EMERGENCY",
            "ALERT",
            "CRITICAL",
            "ERROR",
            "WARNING",
            "NOTICE",
            "INFO",
            "DEBUG"
          ],
          "type": "string"
        },
        "network": {
          "default": "",
          "description": "(OPTIONAL) Network type used by the (r)Syslog",
          "enum": [
            "",
            "udp",
            "tcp"
          ],
          "type": "string"
        }
      },
      "required": [
        "address",
        "level",
        "network"
      ],
      "title": "Logger",
      "type": "object"
    },
    "remoteConfigEndpoint": {
      "default": "",
      "description": "Remote configuration URL (ip:port)",
      "title": "Remote Configuration Endpoint",
      "type": "string"
    },
    "remoteConfigPath": {
      "default": "",
      "description": "Remote configuration path in which to search for the configuration file (e.g. '/config/gogenexample')",
      "title": "Remote Configuration Path",
      "type": "string"
    },
    "remoteConfigProvider": {
      "default": "",
      "description": "Remote configuration source type (if any)",
      "enum": [
        "",
        "consul",
        "etcd",
        "envvar"
      ],
      "title": "Remote Configuration Provider",
      "type": "string"
    },
    "remoteConfigSecretKeyring": {
      "default": "",
      "description": "Path to the openpgp secret keyring used to decrypt the remote configuration data (e.g. '/etc/gogenexample/configkey.gpg'); if empty a non secure connection will be used instead",
      "title": "Remote Configuration Secret Keyring",
      "type": "string"
    },
    "servers": {
      "additionalProperties": false,
      "description": "Configuration for exposed servers",
      "properties": {
        "monitoring": {
          "additionalProperties": false,
          "description": "Configuration for the monitoring server",
          "examples": [
            {
              "address": ":8071",
              "timeout": 60
            }
          ],
          "properties": {
            "address": {
              "default": "",
              "description": "HTTP address (ip:port) or just (:port)",
              "examples": [
                ":8071"
              ],
              "title": "Address",
              "type": "string"
            },
            "timeout": {
              "description": "HTTP request timeout [seconds]",
              "examples": [
                60
              ],
              "title": "Timeout",
              "type": "integer"
            }
          },
          "required": [
            "address",
            "timeout"
          ],
          "title": "Monitoring HTTP server",
          "type": "object"
        },
        "private": {
          "additionalProperties": false,
          "description": "Configuration for the private server",
          "examples": [
            {
              "address": ":8072",
              "timeout": 60
            }
          ],
          "properties": {
            "address": {
              "default": "",
              "description": "HTTP address (ip:port) or just (:port)",
              "examples": [
                ":8072"
              ],
              "title": "Address",
              "type": "string"
            },
            "timeout": {
              "description": "HTTP request timeout [seconds]",
              "examples": [
                60
              ],
              "title": "Timeout",
              "type": "integer"
            }
          },
          "required": [
            "address",
            "timeout"
          ],
          "title": "Private HTTP server",
          "type": "object"
        },
        "public": {
          "additionalProperties": false,
          "description": "Configuration for the public server",
          "examples": [
            {
              "address": ":8073",
              "timeout": 60
            }
          ],
          "properties": {
            "address": {
              "default": "",
              "description": "HTTP address (ip:port) or just (:port)",
              "examples": [
                ":8073"
              ],
              "title": "Address",
              "type": "string"
            },
            "timeout": {
              "description": "HTTP request timeout [seconds]",
              "examples": [
                60
              ],
              "title": "Timeout",
              "type": "integer"
            }
          },
          "required": [
            "address",
            "timeout"
          ],
          "title": "Public HTTP server",
          "type": "object"
        }
      },
      "required": [
        "monitoring",
        "private",
        "public"
      ],
      "title": "Servers",
      "type": "object"
    },
    "shutdown_timeout": {
      "default": 30,
      "description": "Time in seconds to wait on exit for a graceful shutdown.",
      "title": "ShutDown Timeout",
      "type": "integer"
    }
  },
  "required": [
    "clients",
    "db",
    "enabled",
    "log",
    "servers"
  ],
  "title": "Configuration for gogenexample",
  "type": "object"
}

=== tecnickcom/gogen/examples/service/resources/etc/gogenexample/config.json
{
  "clients": {
    "ipify": {
      "address": "https://api.ipify.org",
      "timeout": 1
    }
  },
  "db": {
    "enabled": false,
    "main": {
      "conn_max_idle_count": 5,
      "conn_max_idle_time": 60,
      "conn_max_lifetime": 3600,
      "conn_max_open": 50,
      "dsn": "",
      "timeout_ping": 1
    },
    "read": {
      "conn_max_idle_count": 5,
      "conn_max_idle_time": 60,
      "conn_max_lifetime": 3600,
      "conn_max_open": 50,
      "dsn": "",
      "timeout_ping": 1
    }
  },
  "enabled": true,
  "log": {
    "address": "",
    "format": "JSON",
    "level": "INFO",
    "network": ""
  },
  "remoteConfigEndpoint": "",
  "remoteConfigPath": "",
  "remoteConfigProvider": "",
  "remoteConfigSecretKeyring": "",
  "servers": {
    "monitoring": {
      "address": ":8071",
      "timeout": 60
    },
    "private": {
      "address": ":8072",
      "timeout": 60
    },
    "public": {
      "address": ":8073",
      "timeout": 60
    }
  },
  "shutdown_timeout": 60
}

=== tecnickcom/gogen/examples/service/resources/test/int/gogenexample/config.json
{
  "clients": {
    "ipify": {
      "address": "http://gogenexample_smocker_ipify:8080",
      "timeout": 15
    }
  },
  "db": {
    "enabled": true,
    "main": {
      "conn_max_idle_count": 2,
      "conn_max_idle_time": 60,
      "conn_max_lifetime": 180,
      "conn_max_open": 10,
      "dsn": "dbrw_user:dbrw_pass@tcp(gogenexample_mysql:3306)/gogenexample",
      "timeout_ping": 2
    },
    "read": {
      "conn_max_idle_count": 2,
      "conn_max_idle_time": 60,
      "conn_max_lifetime": 180,
      "conn_max_open": 10,
      "dsn": "dbro_user:dbro_pass@tcp(gogenexample_mysql:3306)/gogenexample",
      "timeout_ping": 2
    }
  },
  "enabled": true,
  "log": {
    "address": "",
    "format": "JSON",
    "level": "DEBUG",
    "network": ""
  },
  "servers": {
    "monitoring": {
      "address": ":8071",
      "timeout": 60
    },
    "private": {
      "address": ":8072",
      "timeout": 60
    },
    "public": {
      "address": ":8073",
      "timeout": 60
    }
  },
  "shutdown_timeout": 60
}

=== tecnickcom/gogen/examples/service/resources/test/int/nuragoexample/config.json
{
  "clients": {
    "ipify": {
      "address": "http://nuragoexample_smocker_ipify:8080",
      "timeout": 15
    }
  },
  "db": {
    "enabled": true,
    "main": {
      "conn_max_idle_count": 2,
      "conn_max_idle_time": 60,
      "conn_max_lifetime": 180,
      "conn_max_open": 10,
      "dsn": "dbrw_user:dbrw_pass@tcp(nuragoexample_mysql:3306)/nuragoexample",
      "timeout_ping": 2
    },
    "read": {
      "conn_max_idle_count": 2,
      "conn_max_idle_time": 60,
      "conn_max_lifetime": 180,
      "conn_max_open": 10,
      "dsn": "dbro_user:dbro_pass@tcp(nuragoexample_mysql:3306)/nuragoexample",
      "timeout_ping": 2
    }
  },
  "enabled": true,
  "log": {
    "address": "",
    "format": "JSON",
    "level": "DEBUG",
    "network": ""
  },
  "servers": {
    "monitoring": {
      "address": ":8071",
      "timeout": 60
    },
    "private": {
      "address": ":8072",
      "timeout": 60
    },
    "public": {
      "address": ":8073",
      "timeout": 60
    }
  },
  "shutdown_timeout": 60
}
